### ISSUE TITLE
Asks me to install .net over and over again

### ISSUE THREAD

**Issue by Jinarra** [MillzyDev/ModpackExtractor#1]
.net is VERY much installed, and I have rebooted after installing to be absolutely certain. 8.0 long-term support release.

**Comment by MillzyDev** [comment]
The release is outdated and uses .NET 5.

**Comment by MillzyDev** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by MillzyDev** [comment]
It would also seem the CurseForge API changed, so this will not work anyway.
I will be archiving the repository now.
